# Generated by Django 5.2.6 on 2025-09-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=150)),
                ('ano_publicacao', models.PositiveIntegerField()),
                ('editora', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
