# Generated by Django 5.2.6 on 2025-10-24 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0003_alter_livro_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=200),
        ),
    ]
