# Generated by Django 5.2.6 on 2025-10-24 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0005_alter_livro_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='nacionalidade',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=150),
        ),
    ]
