# Generated by Django 5.2.8 on 2025-11-10 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0006_remove_autor_nacionalidade_alter_livro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='autor',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livros', to='meusite.autor'),
        ),
    ]
