# Generated by Django 5.2.6 on 2025-11-12 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meusite', '0007_autor_nacionalidade_alter_livro_autor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliador', models.CharField(max_length=100)),
                ('nota', models.PositiveIntegerField()),
                ('comentario', models.TextField(blank=True, null=True)),
                ('data_avaliacao', models.DateTimeField(auto_now_add=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='meusite.livro')),
            ],
        ),
    ]
